### PR TITLE
#161861601 Set up comment like model

### PR DESCRIPTION
**Pull request by KvNGCzA**
#### What does this PR do?
Sets up the comment likes model.

#### Description of Task to be completed?
- set up comment like model
- set up comment like migration file
- create test for comment like model

#### How should this be manually tested?
N/A

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#161861601](https://www.pivotaltracker.com/story/show/161861601)

#### Screenshots (if appropriate)
N/A

#### Questions:
N/A

### CODE REVIEW

**Comment by mbilesanmi** [comment]
Why delete the article seeder file?

**Comment by Darthrighteous** [comment]
@mbilesanmi two article seeder files were created(mistakenly I assume) https://github.com/andela/valinor-ah-backend/tree/develop/server/seeders

**Comment by KvNGCzA** [comment]
> Why delete the article seeder file?

@mbilesanmi there were two seeders files in the develop branch

**Comment by KvNGCzA** [comment]
@Darthrighteous fixed the issue. Thanks for pointing that out

**Pull request merged**
